### ISSUE TITLE
user login 

### ISSUE THREAD

**Issue by gazamcnulty** [gazamcnulty/pp5-babylon-books#6]
"as a **user** I want to be **able to log in to the website** , so that **it displays my username and any activity is linked with my registered account**
"

**Acceptance Criteria**
user can click a login button on the site that says login, it asks them to give their username + password.

**Tasks**
-create html template for login page
-create a form on the page with method POST and labels asking for username + password
-import messages + authenticate, login, logout to views.py
-create a new function based view in views.py using django logic for login
-set urlpatterns path for loginpage

**Comment by VidyaYadavv1519** [comment]
Is this issue still available ??
Can you assign me this issue ??
